export const paths = {
  home: (t: string) => `/${t}`,
  login: (t: string) => `/${t}/login`,
  cadastro: (t: string) => `/${t}/cadastro`,
  classificacao: (t: string) => `/${t}/classificacao`,
  artilharia: (t: string) => `/${t}/artilharia`,
  enquete: (t: string) => `/${t}/enquete`,
  notificacoes: (t: string) => `/${t}/notificacoes`,
  convite: (t: string, token: string) => `/${t}/convite/${token}`,
  atleta: (t: string, id: string) => `/${t}/atleta/${id}`,
  partida: (t: string, id: string) => `/${t}/partida/${id}`,
  admin: {
    root: (t: string) => `/${t}/admin`,
    campeonatos: (t: string) => `/${t}/admin/campeonatos`,
    categorias: (t: string) => `/${t}/admin/categorias`,
    categoria: (t: string, id: string) => `/${t}/admin/categorias/${id}`,
    times: (t: string) => `/${t}/admin/times`,
    time: (t: string, id: string) => `/${t}/admin/times/${id}`,
    partidas: (t: string) => `/${t}/admin/partidas`,
    partida: (t: string, id: string) => `/${t}/admin/partidas/${id}`,
    partidaEditar: (t: string, id: string) => `/${t}/admin/partidas/${id}/editar`,
    partidaSumula: (t: string, id: string) => `/${t}/admin/partidas/${id}/sumula`,
    solicitacoes: (t: string) => `/${t}/admin/solicitacoes`,
    inscricoes: (t: string) => `/${t}/admin/inscricoes`,
    enquetes: (t: string) => `/${t}/admin/enquetes`,
    patrocinadores: (t: string) => `/${t}/admin/patrocinadores`,
    notificacoes: (t: string) => `/${t}/admin/notificacoes`,
  },
  treinador: {
    root: (t: string) => `/${t}/treinador`,
    partidas: (t: string) => `/${t}/treinador/partidas`,
    partidaSumula: (t: string, id: string) => `/${t}/treinador/partidas/${id}/sumula`,
  },
};
